name: Merge Target Branch into PR
inputs:
  target:
    description: 'Target branch'
    required: true
  
runs:
  using: 'composite'
  steps:
    - id: fetch
      name: Fetch latest
      shell: bash
      run: git fetch origin ${{ inputs.target }}

    - id: merge
      name: Merge latest target branch into PR branch
      shell: bash
      run: git merge ${{ inputs.target }}
