name: Merge Target Branch into PR
inputs:
  target:
    description: 'Target branch'
    required: true
  
runs:
  using: 'composite'
  steps:
    - id: fetch
      name: Fetch latest
      shell: bash
      run: git fetch origin ${{ inputs.target }}
    
    - id: set_git_identity
      name: Set git identity
      shell: bash
      run: |
        git config --global user.email "gh-action@inff.com" & \
        git config --global user.name "Composite Action Merge"

    - id: merge
      name: Merge latest target branch into PR branch
      shell: bash
      run: git merge origin/${{ inputs.target }} --allow-unrelated-histories
