name: Dev - Terraform Plan
on:
  pull_request:
    branches:
      - main
    paths:
      - "dev/**"

permissions:
  id-token: write # This is required for requesting the JWT (OIDC)
  contents: read
  pull-requests: write

jobs:
  dev_terraform_plan:
    environment:
      name: Development
    env:
      tf_version: "1.10.2"
      tf_dir: "dev"

    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ${{ env.tf_dir }}

    if: github.event.pull_request.state != 'approved'
    steps:
      - id: checkout_latest
        name: Checkout latest
        uses: actions/checkout@v4

      - id: tf_prep
        name: Terraform setup using Access Key
        uses: ./actions/setup_with_key
        env:
          aws_tfstate_key: "state/terraform-state"
        with:
          terraform_dir: ${{ env.tf_dir }}
          terraform_version: ${{ env.tf_version }}
          aws_region: ${{ secrets.TF_BACKEND_REGION }}
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          aws_tfstate_bucket: ${{ secrets.TF_BACKEND_STATE_BUCKET }}
          aws_tfstate_key: ${{ env.aws_tfstate_key }}
          aws_tflock_table: ${{ secrets.TF_BACKEND_LOCKID_TABLE }}

      - id: tf_plan
        name: Terraform Plan
        run: terraform plan -out .planfile
        env:
          # Non-blank value will overwrite the terraform fetched thumbprint
          TF_VAR_oidc_provider_thumbprint: ""
          TF_VAR_location: ${{ secrets.AWS_REGION }}
          TF_VAR_dev_bootstrap_role: ${{ secrets.AWS_DEV_BOOTSTRAP_ROLE }}
          TF_VAR_central_ecr_region: ${{ secrets.CENTRAL_ECR_REGION }}
          TF_VAR_central_ecr_repo: ${{ secrets.CENTRAL_ECR_REPO }}
          TF_VAR_prod_account_id: ${{ secrets.AWS_PROD_ACCOUNT }}

      - id: publish_tf_plan
        name: Publish Plan to PR and S3
        uses: Innovate-Future-Foundation/common-action/publish-tfplan-s3@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tf_dir: ${{ env.tf_dir }}
          s3_bucket: ${{ secrets.WORKFLOW_TEMP_BUCKET }}
          obj_key: plans/plan-${{ github.event.pull_request.number }}_${{ env.tf_dir }}
