name: Terraform Apply
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      pr_number:
        description: The Pull Request number
        required: true
        type: number


permissions:
  id-token: write # This is required for requesting the JWT (OIDC)
  contents: read
  pull-requests: write

jobs:
  terraform_plan:
    runs-on: ubuntu-22.04
    env:
      terraform_version: "1.1.7"
      # These are for testing purpose
      aws_region: "us-west-2"
      aws_tfstate_bucket: "inff-5u91r-terraform-bootstrap-tfstate"
      aws_tfstate_key: "state/terraform-state"
      aws_tflock_table: "inff-5u91r-terraform-bootstrap-tflock"
    
    steps:
      - id: tf_prep
        name: Terraform setup using Access Key
        uses: ./actions/setup_with_key
        with:
          terraform_dir: "./"
          terraform_version: ${{ env.terraform_version }}
          aws_region: ${{ env.aws_region }}
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          aws_tfstate_bucket: ${{ env.aws_tfstate_bucket }}
          aws_tfstate_key: ${{ env.aws_tfstate_key }}
          aws_tflock_table: ${{ env.aws_tflock_table }}

      - id: get_pr_number
        name: Get PR number
        if: github.event_name == 'push'
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            echo "Getting PR number based on head_commit"
            PR_NUMBER=$(gh pr list --base main --state merged --search "${{ github.event.head_commit.message }}" --json number --jq '.[0].number')
          else
            echo "Getting PR number from dispatch input"
            PR_NUMBER=${{ github.event.inputs.pr_number }}
          fi
          if [ -z "$PR_NUMBER" ]; then
            echo "No matching PR found"
            exit 1
          fi
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - id: dl_tf_plan
        name: Download Plan from S3
        run: |
          aws s3 cp s3://${{ secrets.S3_REPO_ARTIFACT_BUCKET }}/plans/plan-pr_${{ steps.get_pr_number.outputs.PR_NUMBER }} tfplan
          if [ $? -ne 0 ]; then
            echo "Failed to retrieve planfile. It may have expired or been deleted."
            exit 1
          fi

      - id: tf_apply
        name: Terraform Apply
        run: terraform apply -auto-approve tfplan
