name: Terraform Apply
on:
  push:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      pr_number:
        description: The Pull Request number
        required: true
        type: number

permissions:
  id-token: write # This is required for requesting the JWT (OIDC)
  contents: read
  pull-requests: write

jobs:
  terraform_plan:
    runs-on: ubuntu-22.04
    steps:
      - id: checkout_latest
        name: Checkout latest
        uses: actions/checkout@v4
      - id: tf_prep
        name: Terraform setup using Access Key
        uses: ./actions/setup_with_key
        env:
          terraform_version: "1.1.7"
          terraform_dir: "./"
          aws_tfstate_key: "state/terraform-state"
        with:
          terraform_dir: ${{ env.terraform_dir }}
          terraform_version: ${{ env.terraform_version }}
          aws_region: ${{ secrets.AWS_REGION }}
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          aws_tfstate_bucket: ${{ secrets.S3_STATE_FILE_BUCKET }}
          aws_tfstate_key: ${{ env.aws_tfstate_key }}
          aws_tflock_table: ${{ secrets.DYNAMODB_STATE_LOCK_TABLE }}

      - id: get_pr_number
        name: Get PR number
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            echo "Getting PR number based on head_commit"
            PR_NUMBER=$(gh pr list --base main --state merged --search "${{ github.event.head_commit.message }}" --json number --jq '.[0].number')
          else
            echo "Getting PR number from dispatch input"
            PR_NUMBER=${{ github.event.inputs.pr_number }}
          fi
          if [ -z "$PR_NUMBER" ]; then
            echo "No matching PR found"
            exit 1
          fi
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - id: dl_tf_plan
        name: Download Plan from S3
        run: |
          aws s3 cp s3://${{ secrets.S3_REPO_ARTIFACT_BUCKET }}/plans/plan-pr_${{ steps.get_pr_number.outputs.PR_NUMBER }} tfplan
          if [ $? -ne 0 ]; then
            echo "Failed to retrieve planfile. It may have expired or been deleted."
            exit 1
          fi

      - id: tf_apply
        name: Terraform Apply
        run: terraform apply -auto-approve tfplan
